//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GrafMath.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GRAFMATH_DIALOG             103
#define IDS_BUTTON_DRAW                 104
#define IDR_MAINFRAME                   128
#define IDD_HELP_DIALOG                 129
#define IDR_MENU                        130
#define IDI_ICON_GRAPH16                134
#define IDI_ICON_STEIGUNG16             135
#define IDI_ICON_GRAPH32                137
#define IDI_ICON_STEIGUNG32             138
#define IDB_BITMAP1                     139
#define IDI_ICON_WENDEPUNKT32           141
#define IDI_ICON_ABLEITUNG16            142
#define IDI_ICON_ABLEITUNG32            143
#define IDI_ICON_HOCHPUNKT16            144
#define IDI_ICON_HOCHPUNKT32            145
#define IDI_ICON_TIEFPUNKT16            146
#define IDI_ICON_TIEFPUNKT32            147
#define IDI_ICON_WENDEPUNKT16           148
#define IDI_ICON_TANGENTE32             149
#define IDI_ICON_TANGENTE16             150
#define IDI_ICON_SCHNITTPUNKT_YACHSE32  151
#define IDI_ICON_SCHNITTPUNKT_XACHSE16  152
#define IDI_ICON_SCHNITTPUNKT_XACHSE32  153
#define IDI_ICON_SCHNITTPUNKT_YACHSE16  154
#define IDI_ICON_ZOOMOUT_YACHSE32       157
#define IDI_ICON_ZOOMIN_XACHSE16        158
#define IDI_ICON_ZOOMIN_XACHSE32        159
#define IDI_ICON_ZOOMIN_XYACHSE16       160
#define IDI_ICON_ZOOMIN_XYACHSE32       161
#define IDI_ICON_ZOOMIN_YACHSE16        162
#define IDI_ICON_ZOOMIN_YACHSE32        163
#define IDI_ICON_ZOOMOUT_XACHSE16       164
#define IDI_ICON_ZOOMOUT_XACHSE32       165
#define IDI_ICON_ZOOMOUT_XYACHSE16      166
#define IDI_ICON_ZOOMOUT_XYACHSE32      167
#define IDI_ICON_ZOOMOUT_YACHSE16       168
#define IDD_DIALOG_AXISOPTIONS          169
#define IDI_ICON_AXISOPTIONS            170
#define IDI_HELP_ICON                   171
#define IDR_RTF_HILFE                   172
#define IDD_DIALOG_INPUT_FUNCTION       172
#define IDR_POPUP_HELP_MENU             173
#define IDD_DIALOG_GAUSSELIM            173
#define IDI_ICON_OK                     174
#define IDD_DIALOG_VALUETABLE           175
#define IDD_DIALOG_GRADIENT             176
#define IDD_DIALOG_TANGENT              177
#define IDI_ICON_WERTETABELLE32         178
#define IDI_ICON_WERTETABELLE16         179
#define IDI_ICON_SAVE                   180
#define IDI_ICON_OPEN                   181
#define IDD_DIALOG_CREDITS              182
#define IDD_DIALOG_MONOTONY             183
#define IDD_DIALOG_INTEGRAL             184
#define IDD_DIALOG_YAUSX                185
#define IDD_DIALOG_LEN2P                186
#define IDC_BUTTON_DRAW                 1002
#define IDC_BUTTON_ABLEITUNG            1003
#define IDC_BUTTON_TANGENTE             1004
#define IDC_BUTTON_STEIGUNG             1005
#define IDC_BUTTON_SCHNITTPUNKT_XACHSE  1006
#define IDC_BUTTON_SCHNITTPUNKT_YACHSE  1007
#define IDC_BUTTON_ZOOMOUT_XACHSE       1008
#define IDC_BUTTON_WENDEPUNKT           1009
#define IDC_BUTTON_HOCHTIEFPUNKT        1010
#define IDC_BUTTON_VIEW_LOAD            1011
#define IDC_BUTTON_ZOOMIN_XACHSE        1012
#define IDC_BUTTON_ZOOMIN_YACHSE        1013
#define IDC_BUTTON_ZOOMOUT_YACHSE       1014
#define IDC_BUTTON_ZOOMIN_XYACHSE       1015
#define IDC_BUTTON_ZOOMOUT_XYACHSE      1016
#define IDC_BUTTON_GETXYRANGE           1017
#define IDC_CANVAS                      1018
#define IDC_STATIC_MA                   1019
#define IDC_BUTTON_AXISOPTIONS          1019
#define IDC_STATIC_MJ                   1020
#define IDC_STATIC_ES                   1021
#define IDC_BUTTON_VIEW_SAVE            1021
#define IDC_STATIC_PS                   1022
#define IDC_CHECK_AXISDESCRIPTION       1024
#define IDC_EDIT_AXISPARTS              1025
#define IDC_SPIN_COEFFICIENT_A          1026
#define IDC_EDIT_DECIMALPARTS           1027
#define IDC_SPIN_COEFFICIENT_B          1027
#define IDC_SPIN_COEFFICIENT_C          1028
#define IDC_EDIT_HELPAXISWIDTH          1029
#define IDC_SPIN_COEFFICIENT_D          1029
#define IDC_SPIN_HELPAXISWIDTH          1030
#define IDC_BUTTON_DEFAULT              1031
#define IDC_EDIT_COEFFICIENT_A          1032
#define IDC_EDIT_COEFFICIENT_B          1033
#define IDC_BUTTON_INPUT_FUNCTION       1033
#define IDC_EDIT_COEFFICIENT_C          1034
#define IDC_EDIT_NUMB_OF_EQUATIONS      1034
#define IDC_EDIT_COEFFICIENT_D          1035
#define IDC_EDIT_COEFFA11               1035
#define IDC_EDIT_COEFFA12               1036
#define IDC_EDIT_COEFFA13               1037
#define IDC_EDIT_COEFFA14               1038
#define IDC_EDIT_COEFFA15               1039
#define IDC_BUTTON_CALC                 1040
#define IDC_SPIN_AXISPARTS              1042
#define IDC_SPIN_DECIMALPARTS           1043
#define IDC_EDIT_COEFFB1                1044
#define IDC_EDIT_COEFFA21               1045
#define IDC_EDIT_COEFFA22               1046
#define IDC_EDIT_COEFFA23               1047
#define IDC_EDIT_COEFFA24               1048
#define IDC_EDIT_COEFFA25               1049
#define IDC_EDIT_COEFFB2                1050
#define IDC_EDIT_COEFFA31               1051
#define IDC_EDIT_COEFFA32               1052
#define IDC_EDIT_COEFFA33               1053
#define IDC_EDIT_COEFFA34               1054
#define IDC_EDIT_COEFFA35               1055
#define IDC_EDIT_COEFFB3                1056
#define IDC_EDIT_COEFFA41               1057
#define IDC_EDIT_COEFFA42               1058
#define IDC_EDIT_COEFFA43               1059
#define IDC_EDIT_COEFFA44               1060
#define IDC_EDIT_COEFFA45               1061
#define IDC_EDIT_COEFFB4                1062
#define IDC_EDIT_COEFFA51               1063
#define IDC_EDIT_COEFFA52               1064
#define IDC_EDIT_COEFFA53               1065
#define IDC_EDIT_COEFFA54               1066
#define IDC_EDIT_COEFFA55               1067
#define IDC_EDIT_COEFFB5                1068
#define IDC_EDIT_RESULTX1               1070
#define IDC_EDIT_RESULTX2               1071
#define IDC_EDIT_RESULTX3               1072
#define IDC_EDIT_RESULTX4               1073
#define IDC_EDIT_RESULTX5               1074
#define IDC_BUTTON_SET_COEFFICIENTS     1113
#define IDC_EDIT_X_MIN                  1117
#define IDC_EDIT_X_MAX                  1118
#define IDC_LIST_VALUETABLE             1119
#define IDC_EDIT_X_DELTA                1120
#define IDC_EDIT_X                      1122
#define IDC_EDIT_AREA                   1122
#define IDC_EDIT_GRADIENT               1123
#define IDC_EDIT_P2X                    1124
#define IDC_EDIT_P2Y                    1125
#define IDC_EDIT_TANGENT                1126
#define IDC_EDIT_LEN2P                  1126
#define IDC_EDIT_MONOTONY               1131
#define IDC_RADIO_X0                    1132
#define IDC_RADIO_X1                    1133
#define IDC_RADIO_Y0                    1134
#define IDC_RADIO_Y1                    1135
#define IDC_RADIO_X2                    1136
#define IDC_RADIO_Y                     1137
#define IDC_EDIT_Y                      1138
#define IDC_EDIT_P1X                    1139
#define IDC_EDIT_P1Y                    1140
#define IDC_BUTTON_GETY2                1142
#define IDC_BUTTON_GETY1                1143
#define ID_POPUP_HELP_PRINT             32768
#define ID_FILE_KEEPHELPONTOP_ONTOP     32769
#define ID_FILE_KEEPHELPONTOP_NOTONTOP  32770
#define ID_MNU_APP_HILFE                32771
#define ID_MNU_MISC_GAUSS_ELIMINATON    32772
#define ID_MNU_PUNKT_SATTELPUNKT        32776
#define ID_MNU_PUNKT_WENDESTELLE        32777
#define ID_MNU_PUNKT_MINIMA_MAXIMA      32778
#define ID_MNU_PUNKT_HOCHTIEF           32779
#define ID_MNU_MISC_STEIGUNG            32780
#define ID_MNU_MISC_TANGENTE_GLEICHUNG  32782
#define ID_MNU_MISC_ABLEITUNGEN         32783
#define ID_MNU_PUNKT_SCHNITTSTELLEN_XACHSE 32795
#define ID_MNU_PUNKT_SCHNITTSTELLEN_YACHSE 32796
#define ID_MNU_MISC_GAUSS_ELIMINATION   32797
#define ID_MNU_FUNKTION_EINGEBEN        32799
#define ID_MNU_FUNKTION_ZEICHNEN        32800
#define ID_MNU_FUNKTION_EINGEBENUNDZEICHNEN 32801
#define ID_MNU_MISC_ACHSENSYMMETRIE     32802
#define ID_MNU_ACHSEN_ACHSENSKALIERUNG_ZOOMIN_XY 32803
#define ID_MNU_ACHSEN_ACHSENSKALIERUNG_ZOOMOUT_XY 32804
#define ID_MNU_ACHSEN_EINSTELLUNGEN     32805
#define ID_MNU_ACHSEN_ANZEIGE_SKALIERUNG 32806
#define ID_MNU_MISC_WERTETABELLE        32807
#define ID_MNU_APP_ANSICHTLADEN         32808
#define ID_MNU_APP_ANSICHTSPEICHERN     32809
#define ID_MNU_APP_CREDITS              32810
#define ID_MNU_MISC_AUFLEITUNG          32811
#define ID_MNU_MISC_FLAECHENBERECHNUNG  32812
#define ID_MNU_PUNKT_SCHEITELPUNKT      32813
#define ID_MNU_MISC_MONOTONIE           32814
#define ID_MNU_MISC_YAUSX               32815
#define ID_MNU_MISC_LAENGE2P            32816
#define IDS_INDICATOR_TIME              0xE141
#define IDS_INDICATOR_NISH              57666
#define IDS_SCHNITTPUNKT_XACHSE         57667
#define IDS_SCHNITTPUNKT_YACHSE         57668
#define IDS_WENDESTELLE                 57671
#define IDS_ABLEITUNG                   57672
#define IDS_TANGENTE                    57674
#define IDS_ZOOMOUT_XYACHSE             57675
#define IDS_ZOOMIN_XYACHSE              57676
#define IDS_ZOOMIN_XACHSE               57677
#define IDS_ZOOMOUT_YACHSE              57678
#define IDS_ZOOMIN_YACHSE               57679
#define IDS_ZOOMOUT_XACHSE              57680
#define IDS_GRAPHZEICHNEN               57681
#define IDS_GETXYRANGE                  57682
#define IDS_EDIT_FUNCTION               57683
#define IDS_AXISOPTIONS                 57684
#define IDS_INPUTFUNCTION               57685
#define IDS_ANSICHT_SPEICHERN           57686
#define IDS_ANSICHT_LADEN               57687

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        187
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
