//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LscGen.rc
//
#define IDR_MANIFEST                    1
#define IDC_BUTTON_HM_PREVIEW           3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LSCGEN_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDI_ICON_LSCGEN                 128
#define IDB_BITMAP_BANNER               132
#define IDI_ICON_MSVC7                  133
#define IDI_ICON_MFC7                   134
#define IDI_ICON_MFC                    135
#define IDI_ICON_MSVC6                  136
#define IDI_ICON_LSC_NEW                138
#define IDI_ICON_LSC_SAVE               139
#define IDI_ICON_LSC_EDIT               140
#define IDI_ICON_LSC_LOAD               141
#define IDI_ICON_HEIGHTFIELD            142
#define IDI_ICON_MODEL                  143
#define IDI_ICON_APP_ABOUT              144
#define IDI_ICON_APP_EXIT               145
#define IDD_DIALOG_LSC_NEW              146
#define IDI_ICON_BOOK_OPEN              147
#define IDI_ICON_BOOK                   148
#define IDI_ICON_CLIPBOARD_EMPTY        149
#define IDI_ICON_CHECK2                 150
#define IDI_ICON_CHECK                  151
#define IDI_ICON_CLIPBOARD              152
#define IDI_ICON_DELETE                 153
#define IDI_ICON_COLORS                 154
#define IDI_ICON_COPY                   155
#define IDI_ICON_CUT                    156
#define IDI_ICON_DATABASE               157
#define IDI_ICON_DELETE2                158
#define IDI_ICON_DOWNLOAD               159
#define IDI_ICON_DOC_CHECK              160
#define IDI_ICON_DOC_INFO               161
#define IDI_ICON_DOC_PREF               162
#define IDI_ICON_DOC_VIEW               163
#define IDI_ICON_EXCHANGE               164
#define IDI_ICON_EDIT2                  165
#define IDI_ICON_ENVIROMENT             166
#define IDI_ICON_ERROR                  167
#define IDI_ICON_HELP_ONLINE            168
#define IDI_ICON_FAQ                    169
#define IDI_ICON_FITTOSIZE              170
#define IDI_ICON_LSC_CLOSE              171
#define IDI_ICON_FORBIDDEN              172
#define IDI_ICON_GEAR                   173
#define IDI_ICON_HELP2                  175
#define IDI_ICON_LOGIC_OR               176
#define IDI_ICON_IDCARD                 177
#define IDI_ICON_INFORMATION            178
#define IDI_ICON_LIGHTBULB              179
#define IDI_ICON_LIGHTBULB_ON           180
#define IDI_ICON_LOGIC_AND              181
#define IDI_ICON_LOGIC_NOT              182
#define IDI_ICON_NAVIGATE_UP            183
#define IDI_ICON_MAIL                   184
#define IDI_ICON_NAV_DOWN_GREEN         185
#define IDI_ICON_NAV_LEFT_GREEN         186
#define IDI_ICON_NAV_PLAIN_GREEN        187
#define IDI_ICON_NAV_RIGHT_GREEN        188
#define IDI_ICON_NAV_UP_GREEN           189
#define IDI_ICON_NAVIGATE_CROSS         190
#define IDI_ICON_NAVIGATE_DOWN          191
#define IDI_ICON_NAVIGATE_LEFT          192
#define IDI_ICON_NAVIGATE_MINUS         193
#define IDI_ICON_NAVIGATE_PLUS          194
#define IDI_ICON_NAVIGATE_RIGHT         195
#define IDI_ICON_PHOTO_SCENERY          196
#define IDI_ICON_NOTEBOOK               197
#define IDI_ICON_NOTEBOOK_PREF          198
#define IDI_ICON_PASTE                  199
#define IDI_ICON_PHOTO_PORTRAIT         200
#define IDI_ICON_RECYCLE                201
#define IDI_ICON_REDO                   202
#define IDI_ICON_REFRESH                203
#define IDI_ICON_SCRIPT                 204
#define IDI_ICON_STOP                   205
#define IDI_ICON_TRANSFORM2             206
#define IDI_ICON_TRANSFORM              207
#define IDI_ICON_UNDO                   208
#define IDI_ICON_UNKNOWN                209
#define IDI_ICON_WARNING                210
#define IDI_ICON_WINDOW_EARTH           211
#define IDI_ICON_WINDOW_EDIT            212
#define IDI_ICON_WINDOW_ENVIROMENT      213
#define IDI_ICON_WINDOW_GEAR            214
#define IDI_ICON_WINDOW_INFO            215
#define IDI_ICON_WINDOW_NEW             216
#define IDI_ICON_NAVIGATE_CROSS2        219
#define IDI_ICON_VRML                   220
#define IDI_ICON_X3D                    221
#define IDD_DIALOG_EXPORTAS_MODEL       222
#define IDD_DIALOG_EXPORTAS_GRAPHIC     223
#define IDD_DIALOG_LSC_EDIT             224
#define IDI_ICON_ARROW_UP_BLUE          225
#define IDI_ICON_ARROW_DOWN_BLUE        226
#define IDI_ICON_ARROW_LEFT_BLUE        227
#define IDI_ICON_ARROW_RIGHT_BLUE       228
#define IDI_ICON_MIRROR_HORI            231
#define IDI_ICON_MIRROR_VERT            232
#define IDI_ICON_INVERT                 233
#define IDI_ICON_GLACIATE               234
#define IDD_DIALOG_HM_PREVIEW           235
#define IDC_BUTTON_LSC_NEW              1000
#define IDC_BUTTON_RAISE                1000
#define IDC_BUTTON_LSC_LOAD             1001
#define IDC_BUTTON_EXPORTAS_X3D         1001
#define IDC_BUTTON_FLAT                 1001
#define IDC_BUTTON_LSC_SAVE             1002
#define IDC_EDIT_LSC_NAME               1002
#define IDC_BUTTON_EXPORTAS_XPM         1002
#define IDC_BUTTON_GLACIATE             1002
#define IDC_BUTTON_LSC_EDIT             1003
#define IDC_COMBO_ALGORITHM             1003
#define IDC_BUTTON_ROTATE_LEFT          1003
#define IDC_BUTTON_EXPORTAS_MODEL       1004
#define IDC_RADIO_METHOD1               1004
#define IDC_BUTTON_ROTATE_RIGHT         1004
#define IDC_BUTTON_EXPORTAS_GRAPHIC     1005
#define IDC_RADIO_METHOD2               1005
#define IDC_BUTTON_INVERT               1005
#define IDC_BUTTON_APP_ABOUT            1006
#define IDC_EDIT_METHOD2                1006
#define IDC_BUTTON_HORIZONTAL           1006
#define IDC_BUTTON_APP_EXIT             1007
#define IDC_EDIT_METHOD1                1007
#define IDC_BUTTON_VERTICAL             1007
#define IDC_BUTTON_EXPORTAS_SQL         1008
#define IDC_EDIT_SIZEX                  1008
#define IDC_EDIT_LSC_NAME2              1008
#define IDC_BUTTON_LSC_CLOSE            1009
#define IDC_RADIO_START_XY              1009
#define IDC_EDIT_SIZEY                  1010
#define IDC_EDIT_START_X                1011
#define IDC_EDIT_START_Y                1012
#define IDC_RADIO_START_RANDOM          1013
#define IDC_RADIO_HEIGHT_ASC_WITH       1017
#define IDC_RADIO_START_MIDPOINT        1018
#define IDC_EDIT_ROUTE_RIGHT            1019
#define IDC_EDIT_ROUTE_LEFT             1020
#define IDC_EDIT_ROUTE_DOWN             1021
#define IDC_EDIT_ROUTE_UP               1022
#define IDC_EDIT_LSC_COMMENTS           1023
#define IDC_EDIT_HEIGHT_ASC_WITH        1024
#define IDC_RADIO_HEIGHT_ASC_BETWEEN    1025
#define IDC_EDIT_HEIGHT_ASC_BETWEEN_FROM 1026
#define IDC_EDIT_HEIGHT_ASC_BETWEEN_TO  1027
#define IDC_CHECK_HEIGHT_DESC           1028
#define IDC_EDIT_HEIGHT_DESC_AT         1029
#define IDC_EDIT_HEIGHT_DESC_AFTER      1030
#define IDC_CHECK_RANGE                 1031
#define IDC_RADIO_CANYONIZE1            1040
#define IDC_RADIO_CANYONIZE2            1041
#define IDC_BUTTON_EXPORTAS_VRML        1042
#define IDC_BUTTON_GENERATE             1043
#define IDC_BUTTON_EXPORTAS_PGM         1044
#define IDC_BUTTON_EXPORTAS_RAW         1045
#define IDC_PROGRESS_GENERATE           1053
#define IDC_EDIT_LSC_COMMENTS2          1055
#define IDC_BUTTON_DOWN2                1060
#define IDC_BUTTON_RIGHT2               1061
#define IDC_BUTTON_LEFT2                1062
#define IDC_BUTTON_UP2                  1063
#define IDC_BUTTON_CANYONIZE            1064

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        236
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
